default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :database_password) %>

development:
  <<: *default
  database: olist_development

test:
  <<: *default
  database: olist_test

production:
  <<: *default
  database: olist_production
